# Brainstorm

### Source 1:

Where did you download the data (e.g., a web URL: [https://fred.stlouisfed.org/series/FEDFUNDS](https://fred.stlouisfed.org/series/FEDFUNDS))?

**How was the data collected or generated? Make sure to explain who collected the data (not necessarily the same people that host the data), and who or what the data is about?**
<br />The data is about the Effective Federal Funds Rate that collected by the Federal Reserve Bank of St. Louis. It shows the percentage of the interest rate from 1955 to the present.

**How many observations (rows) are in your data?**
<br />1568

**How many features (columns) are in the data?**
<br />2 features (Time/ Rate)

**What questions (from above) can be answered using the data in this dataset?**
<br />The data provides an overview of the interest rate for over 60 years. Based on the information, we can see the fluctuations over the years.


### Source 2:

Where did you download the data (e.g., a web URL: [https://finance.yahoo.com/quote/UGE?p=UGE](https://finance.yahoo.com/quote/UGE?p=UGE))?

**How was the data collected or generated? Make sure to explain who collected the data (not necessarily the same people that host the data), and who or what the data is about?**
<br />The data is about the monthly stock price for the ProShares Ultra Consumer Goods (UGE) provided by the New York Stock Exchange Arca from 02/01/2007 until present.

**How many observations (rows) are in your data?**
<br />155

**How many features (columns) are in the data?**
<br />7 features (Date/ Open/ High/ Low/ Close/ Adj Close/ Volume)

**What questions (from above) can be answered using the data in this dataset?**
<br />The data provides insights about the fluctuation of consumer good stock price over 12 years.


### Source 3:

Where did you download the data (e.g., a web URL: [https://finance.yahoo.com/quote/QTEC/profile?p=QTEC](https://finance.yahoo.com/quote/QTEC/profile?p=QTEC))?

**How was the data collected or generated? Make sure to explain who collected the data (not necessarily the same people that host the data), and who or what the data is about?**
<br />The data is about the monthly stock price for the ProShares Ultra Consumer Goods (UGE) provided by the New York Stock Exchange from 05/02/2006 until present.

**How many observations (rows) are in your data?**
<br />164

**How many features (columns) are in the data?**
<br />7 features (Date/ Open/ High/ Low/ Close/ Adj Close/ Volume)

**What questions (from above) can be answered using the data in this dataset?**
<br />The data provides insights about the fluctuation of technology sector stock price over 13 years.
